[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

[build]
  command = "npm ci && npm run build" # Switched from 'bun run build' to 'npm run build'
  publish = "out" # Updated to match Next.js static export directory
  command = "npm cache clean --force && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"
  HUSKY = "0" # Disable husky if not required during builds

[build.cache]
  paths = ["node_modules", ".next/cache"]
  
[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    # Uncomment and customize additional headers if needed
    # Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    # Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Add more redirects if necessary
  # Example:
  # [[redirects]]
  #   from = "/old-path/*"
  #   to = "/new-path/:splat"
  #   status = 301
